"""
Critic Agent — evaluates the generated answer for relevance,
accuracy, completeness and decides whether to approve.
"""

from __future__ import annotations

from agents.base import BaseAgent
from core.llm import generate_json
from models import (
    AgentRole,
    CriticEvaluation,
    PlannerOutput,
    ReasoningOutput,
    ResearchOutput,
)

SYSTEM_PROMPT = """You are the Critic Agent in a multi-agent AI system.
You evaluate the quality of an answer generated by the Reasoning Agent.

You receive:
  1. The original query.
  2. The plan.
  3. Research evidence.
  4. The generated answer.

Return ONLY valid JSON:
{
  "relevance_score": 0.0-1.0,
  "accuracy_score": 0.0-1.0,
  "completeness_score": 0.0-1.0,
  "overall_score": 0.0-1.0,
  "feedback": "<detailed evaluation>",
  "improvements": ["<suggestion1>", "<suggestion2>"],
  "approved": true/false
}

Scoring guide:
- relevance:    Does the answer address what was asked?
- accuracy:     Is the information correct per the evidence?
- completeness: Are all subtasks covered?
- overall:      Weighted composite.
- approved:     true if overall ≥ 0.6
"""


class CriticAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentRole.CRITIC)

    async def execute(
        self,
        query: str,
        plan: PlannerOutput,
        research: list[ResearchOutput],
        answer: ReasoningOutput,
    ) -> CriticEvaluation:
        evidence_summary = ""
        for r in research:
            evidence_summary += f"\n[Subtask {r.subtask_id}] "
            evidence_summary += r.combined_context[:400]

        prompt = f"""Original query: {query}

Plan:
{chr(10).join(f"- {st.description}" for st in plan.subtasks)}

Evidence:
{evidence_summary}

Generated answer:
{answer.answer}

Answer confidence: {answer.confidence}
Answer sources: {', '.join(answer.sources[:10])}

Evaluate this answer as JSON."""

        data = await generate_json(prompt, system=SYSTEM_PROMPT)

        def _score(key: str) -> float:
            return min(max(float(data.get(key, 0.5)), 0.0), 1.0)

        return CriticEvaluation(
            relevance_score=_score("relevance_score"),
            accuracy_score=_score("accuracy_score"),
            completeness_score=_score("completeness_score"),
            overall_score=_score("overall_score"),
            feedback=data.get("feedback", ""),
            improvements=data.get("improvements", []),
            approved=data.get("approved", False),
        )
